# Generated by Django 4.1.1 on 2022-10-03 08:37

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("flex", "0002_flexpage_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "title_and_text",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Add your title", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.TextBlock(
                                        help_text="Add additional text", required=True
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("richtext_block", streams.blocks.RichtextBlock()),
                    ("simple_richtext_block", streams.blocks.SimpleRichtextBlock()),
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
