# Generated by Django 4.1.1 on 2022-10-04 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("blog", "0004_blogcategory_blogdetailspage_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoPage",
            fields=[
                (
                    "blogdetailspage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.blogdetailspage",
                    ),
                ),
                ("youtube_video_id", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
            bases=("blog.blogdetailspage",),
        ),
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "blogdetailspage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="blog.blogdetailspage",
                    ),
                ),
                ("subtitle", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "intro_image",
                    models.ForeignKey(
                        help_text="Best size for this image is 1400x400",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("blog.blogdetailspage",),
        ),
    ]
